[build]
  publish = "."

# Language-prefixed page rewrites (ensure specific pages resolve correctly)
[[redirects]]
  from = "/:lang/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/:lang/gdt"
  to = "/gdt.html"
  status = 200

[[redirects]]
  from = "/:lang/intelligentleman"
  to = "/intelligentleman.html"
  status = 200

[[redirects]]
  from = "/:lang/contact.html"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/:lang/gdt.html"
  to = "/gdt.html"
  status = 200

[[redirects]]
  from = "/:lang/intelligentleman.html"
  to = "/intelligentleman.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/de/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fr/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fi/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/de"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fr"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fi"
  to = "/index.html"
  status = 200
  force = true

# Handle direct access to language-specific pages
[[redirects]]
  from = "/en/contact.html"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/de/contact.html"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/fr/contact.html"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/en/gdt.html"
  to = "/gdt.html"
  status = 200

[[redirects]]
  from = "/de/gdt.html"
  to = "/gdt.html"
  status = 200

[[redirects]]
  from = "/fr/gdt.html"
  to = "/gdt.html"
  status = 200

[[redirects]]
  from = "/en/intelligentleman.html"
  to = "/intelligentleman.html"
  status = 200

[[redirects]]
  from = "/de/intelligentleman.html"
  to = "/intelligentleman.html"
  status = 200

[[redirects]]
  from = "/fr/intelligentleman.html"
  to = "/intelligentleman.html"
  status = 200

# Headers for better caching
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400" 

# Cache images aggressively with immutable fingerprints (adjust if using file hashing)
[[headers]]
  for = "*.{png,jpg,jpeg,webp,avif,svg,gif,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/ 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-src https://www.google.com/recaptcha/; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/contact.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/ 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-src https://www.google.com/recaptcha/; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/gdt.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/intelligentleman.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"